logging:
  level:
    robert: DEBUG

spring:
  profiles:
    active: dev

  datasource:
      tomcat:
        max-active: 12
        max-wait: 5000

robert:
  user:
    password: Passwd.123
    username: test@t.pl